development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:11e70d5360e029afef676491021bbe5c@pike.redistogo.com:9802/
  channel_prefix: restaurant_production
